# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b7008bb8de00ed5cf2f425d8b6c5bb33197379d7b5f9b81b1d21b1dd0d3dc4fefabca8a36660cab87c71e1acf96ea116e5eb599a261460df397896dc082f06

test:
  secret_key_base: c5670854790d4e6f90e4c8bfa0fc358efa8741429616892c21c6b41b0525dcbc4cfc2fdf5ae34f2352490d0a2eb3a2a3f1c203c993d51301f521b74103a8d705

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
